package com.layout;

import com.Serv_Inter.CLASECLIENTES;
import com.Serv_Inter.CLASECOMERCIO;
import com.Serv_Inter.CLASEEMPRESA;
import com.Serv_Inter.CLASEEQUIPO;
import com.Serv_Inter.CLASEMOVIMIENTOS;
import com.Serv_Inter.CLASESERVICIOS;
import com.Serv_Inter.CLASEZONA;
import com.Serv_Inter.ClaseReportAllContratos;
import com.Serv_Inter.Handler;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ReporteContratos extends javax.swing.JFrame {

    private ArrayList<CLASEEMPRESA> empresas;
    private ArrayList<CLASEZONA> zonas;
    private ArrayList<CLASECOMERCIO> comercios;
    private ArrayList<CLASECLIENTES> clientes;
    private ArrayList<CLASEEQUIPO> equipos;
    private ArrayList<CLASEMOVIMIENTOS> movimientos;
    private ArrayList<CLASESERVICIOS> servicios;
    private ArrayList<ClaseReportAllContratos> allContratos;
    String fechaComoCadenaInicio;
    String fechaComoCadenaFinal;
    int cont=0;
    private Handler handler;
private int tipo;
    public ReporteContratos(int t) {
        tipo=t;
        initComponents();
        init();
        this.setLocationRelativeTo(null);
        handler.createViewContratosGral();
    }

    public void init() {
        this.setVisible(true);
        handler = new Handler();
        updateArrays();
    }

    private void updateArrays() {
        empresas = handler.showEmpresas();
        zonas = handler.showZonas();
        comercios = handler.showComercios();
        clientes = handler.showClientes();
        equipos = handler.showEquipos();
        movimientos = handler.showMovimientos();
        servicios = handler.showServicios();
        
    }

    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        for (int i = (model.getRowCount()); i < allContratos.size(); i++) {
            cont = cont+1;
            ClaseReportAllContratos tmp = allContratos.get(i);
            Object[] rowData = new Object[]{tmp.getNoContrato(), tmp.getStatus(), tmp.getNombreEmpresa(), tmp.getNombreComercial(), tmp.getLocalizacionZona(), tmp.getTipoServicio(), tmp.getVelDescarga(),tmp.getVelSubida(), tmp.getNoSerie(), tmp.getFecha(), tmp.getIdMovimiento()};
            model.addRow(rowData);
        }
        jTable1.updateUI();
        String cad;
        cad = Integer.toString(cont);
        jTextField1.setText(cad);
        cont = 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonLocZona = new javax.swing.JRadioButton();
        jRadioButtonStatus = new javax.swing.JRadioButton();
        jRadioButtonNomComer = new javax.swing.JRadioButton();
        jRadioButtonNinguno = new javax.swing.JRadioButton();
        jButtonBuscar = new javax.swing.JButton();
        jComboBoxFiltro = new javax.swing.JComboBox();
        jRadioButtonTipoServ = new javax.swing.JRadioButton();
        jRadioButtonNoContrato = new javax.swing.JRadioButton();
        jRadioButtonEmpresa = new javax.swing.JRadioButton();
        jRadioButtonFecha = new javax.swing.JRadioButton();
        DateChooserInicio = new com.toedter.calendar.JDateChooser();
        DateChooserFinal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButtonFecha = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte Zonas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NoContrato", "Status", "Nom. Empresa", "Nom. Comercial", "Localizacion Zona", "Tipo Servicio", "Vel. Desc.", "Vel. Sub.", "NoSerie", "Fecha", "Id Movimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Detalle de Contratos:");

        jLabel7.setText("Filtrado de busqueda:");

        buttonGroup1.add(jRadioButtonLocZona);
        jRadioButtonLocZona.setText("Localizacion Zona");
        jRadioButtonLocZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLocZonaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonStatus);
        jRadioButtonStatus.setText("Status");
        jRadioButtonStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStatusActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNomComer);
        jRadioButtonNomComer.setText("Nombre Comercial");
        jRadioButtonNomComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNomComerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNinguno);
        jRadioButtonNinguno.setSelected(true);
        jRadioButtonNinguno.setText("Ninguno");
        jRadioButtonNinguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNingunoActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTipoServ);
        jRadioButtonTipoServ.setText("Tipo de Servicio");
        jRadioButtonTipoServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTipoServActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNoContrato);
        jRadioButtonNoContrato.setText("No Contrato");
        jRadioButtonNoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoContratoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonEmpresa);
        jRadioButtonEmpresa.setText("Empresa");
        jRadioButtonEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmpresaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFecha);
        jRadioButtonFecha.setText("Fechas");
        jRadioButtonFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFechaActionPerformed(evt);
            }
        });

        DateChooserInicio.setDateFormatString("yyyy-MM-dd");

        DateChooserFinal.setDateFormatString("yyyy-MM-dd");

        jLabel3.setText("Fecha de inicio:");

        jButtonFecha.setText("Buscar por fecha");
        jButtonFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechaActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha final:");

        jLabel1.setText("Número de registros seleccionados: ");

        jTextField1.setEditable(false);
        jTextField1.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonNinguno)
                                        .addComponent(jLabel7))
                                    .addGap(44, 44, 44))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButtonStatus, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jRadioButtonNomComer)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jRadioButtonNoContrato)
                                                .addGap(6, 6, 6)))
                                        .addComponent(jRadioButtonEmpresa, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonTipoServ, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonLocZona, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(37, 37, 37)))
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxFiltro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonFecha)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateChooserFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateChooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNinguno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonLocZona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNomComer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNoContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEmpresa)
                        .addGap(4, 4, 4)
                        .addComponent(jRadioButtonTipoServ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(DateChooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(DateChooserFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFecha)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonLocZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLocZonaActionPerformed
        jComboBoxFiltro.removeAllItems();
        for (int i = 0; i < zonas.size(); i++) {
            jComboBoxFiltro.addItem(zonas.get(i).getLocalizacion());
        }
    }//GEN-LAST:event_jRadioButtonLocZonaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            String dataf = jComboBoxFiltro.getSelectedItem().toString();
            if (jRadioButtonNinguno.isSelected()) {
                allContratos = handler.showReportViewContratosGral();
                updateTable();
                
            } else if (jRadioButtonLocZona.isSelected()) {
                allContratos = handler.showRepZonasFiltroLocZona(dataf);
                updateTable();
            } else if (jRadioButtonStatus.isSelected()) {
                allContratos = handler.showRepZonasFiltroStatus(dataf);
                updateTable();
            } else if (jRadioButtonNomComer.isSelected()) {
                allContratos = handler.showRepZonasFiltroNomComer(dataf);
                updateTable();
            } else if (jRadioButtonNoContrato.isSelected()) {
                allContratos = handler.showRepZonasFiltroNoContrato(dataf);
                updateTable();
            }else if (jRadioButtonEmpresa.isSelected()) {
                allContratos = handler.showRepZonasFiltroEmpresa(dataf);
                updateTable();
            }else if (jRadioButtonTipoServ.isSelected()) {
                allContratos = handler.showRepZonasFiltroTipoServ(dataf);
                updateTable();
            }
        } catch (Exception e) {
               allContratos = handler.showReportViewContratosGral();
                updateTable(); 
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jRadioButtonStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStatusActionPerformed
        jComboBoxFiltro.removeAllItems();
        for (int i = 0; i < clientes.size(); i++) {
            jComboBoxFiltro.addItem(clientes.get(i).getStatus());
        }
    }//GEN-LAST:event_jRadioButtonStatusActionPerformed

    private void jRadioButtonNomComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNomComerActionPerformed
        jComboBoxFiltro.removeAllItems();
        for (int i = 0; i < comercios.size(); i++) {
            jComboBoxFiltro.addItem(comercios.get(i).getNombreComercial());
        }
    }//GEN-LAST:event_jRadioButtonNomComerActionPerformed

    private void jRadioButtonNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNingunoActionPerformed
        jComboBoxFiltro.removeAllItems();
    }//GEN-LAST:event_jRadioButtonNingunoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new Principal(tipo).setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jRadioButtonNoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoContratoActionPerformed
        jComboBoxFiltro.removeAllItems();
        for (int i = 0; i < clientes.size(); i++) {
            jComboBoxFiltro.addItem(clientes.get(i).getNoContrato());
        }
    }//GEN-LAST:event_jRadioButtonNoContratoActionPerformed

    private void jRadioButtonEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmpresaActionPerformed
        jComboBoxFiltro.removeAllItems();
        for (int i = 0; i < empresas.size(); i++) {
            jComboBoxFiltro.addItem(empresas.get(i).getNombre());
        }
    }//GEN-LAST:event_jRadioButtonEmpresaActionPerformed

    private void jRadioButtonTipoServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTipoServActionPerformed
        jComboBoxFiltro.removeAllItems();
        for (int i = 0; i < servicios.size(); i++) {
            jComboBoxFiltro.addItem(servicios.get(i).getTipo());
        }
    }//GEN-LAST:event_jRadioButtonTipoServActionPerformed

    private void jRadioButtonFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFechaActionPerformed
        // TODO add your handling code here:
        jRadioButtonFecha.setSelected(true);
    }//GEN-LAST:event_jRadioButtonFechaActionPerformed

    private void jButtonFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaActionPerformed

        if (jRadioButtonFecha.isSelected()) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat sdf2= new SimpleDateFormat("yyyy-MM-dd");
            fechaComoCadenaInicio = sdf.format(DateChooserInicio.getDate());
            fechaComoCadenaFinal = sdf2.format(DateChooserFinal.getDate());
            allContratos = handler.showReportViewContratosFiltroFechas(fechaComoCadenaInicio, fechaComoCadenaFinal);
            updateTable();
        }
    }//GEN-LAST:event_jButtonFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooserFinal;
    private com.toedter.calendar.JDateChooser DateChooserInicio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonFecha;
    private javax.swing.JComboBox jComboBoxFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButtonEmpresa;
    private javax.swing.JRadioButton jRadioButtonFecha;
    private javax.swing.JRadioButton jRadioButtonLocZona;
    private javax.swing.JRadioButton jRadioButtonNinguno;
    private javax.swing.JRadioButton jRadioButtonNoContrato;
    private javax.swing.JRadioButton jRadioButtonNomComer;
    private javax.swing.JRadioButton jRadioButtonStatus;
    private javax.swing.JRadioButton jRadioButtonTipoServ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
