package com.layout;

import com.Serv_Inter.CLASECIUDAD;
import com.Serv_Inter.CLASECOMERCIO;
import com.Serv_Inter.CLASEEMPRESA;
import com.Serv_Inter.CLASEESTADO;
import com.Serv_Inter.CLASEZONA;
import com.Serv_Inter.ClaseReportAllZonas;
import javax.swing.JOptionPane;
import com.Serv_Inter.Handler;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ReporteZonas extends javax.swing.JFrame {

    private ArrayList<CLASEEMPRESA> empresas;
    private ArrayList<CLASEZONA> zonas;
    private ArrayList<CLASECIUDAD> ciudades;
    private ArrayList<CLASEESTADO> estados;
    private ArrayList<CLASECOMERCIO> comercios;
    private ArrayList<ClaseReportAllZonas> allZonas;
    private Handler handler;
    private int tipo;
    public ReporteZonas(int t) {
        tipo=t;
        initComponents();
        init();
        this.setLocationRelativeTo(null);
    }

    public void init() {
        this.setVisible(true);
        handler = new Handler();
        this.setLocationRelativeTo(null);
        updateArrays();
        updateEmpresas();
        jRadioButtonNingunoActionPerformed(null);
    }

    private void updateEmpresas() {
        jComboBoxEmpresas.removeAllItems();
        for (int i = 0; i < empresas.size(); i++) {
            CLASEEMPRESA tmp = empresas.get(i);
            jComboBoxEmpresas.addItem("" + tmp.getNombre());
        }
        jComboBoxEmpresas.updateUI();
    }

    private void updateArrays() {
        empresas = handler.showEmpresas();
        zonas = handler.showZonas();
        ciudades = handler.showCiudades();
        estados = handler.showEstados();
        comercios = handler.showComercios();
    }

    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        for (int i = (model.getRowCount()); i < allZonas.size(); i++) {
            ClaseReportAllZonas tmp = allZonas.get(i);
            Object[] rowData = new Object[]{tmp.getIDZONA(), tmp.getLocalizacion(), tmp.getEmpresa(),tmp.getNombreComercial(), tmp.getEstado(), tmp.getCiudad()};
            model.addRow(rowData);
        }
        jTable1.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonCiudad = new javax.swing.JRadioButton();
        jRadioButtonEstado = new javax.swing.JRadioButton();
        jRadioButtonNomComer = new javax.swing.JRadioButton();
        jRadioButtonNinguno = new javax.swing.JRadioButton();
        jButtonBuscarZonas = new javax.swing.JButton();
        jComboBoxFiltro = new javax.swing.JComboBox();
        jComboBoxEmpresas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte Zonas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Zona", "Localización", "Empresa", "Nombre Comercial", "Estado", "Ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Detalle de Zonas:");

        jLabel7.setText("Filtrado de busqueda:");

        buttonGroup1.add(jRadioButtonCiudad);
        jRadioButtonCiudad.setText("Ciudad");
        jRadioButtonCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCiudadActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonEstado);
        jRadioButtonEstado.setText("Estado");
        jRadioButtonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEstadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNomComer);
        jRadioButtonNomComer.setText("Nombre Comercial");
        jRadioButtonNomComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNomComerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNinguno);
        jRadioButtonNinguno.setSelected(true);
        jRadioButtonNinguno.setText("Ninguno");
        jRadioButtonNinguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNingunoActionPerformed(evt);
            }
        });

        jButtonBuscarZonas.setText("Buscar Zonas");
        jButtonBuscarZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarZonasActionPerformed(evt);
            }
        });

        jLabel1.setText("Empresas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxEmpresas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jRadioButtonEstado)
                            .addComponent(jRadioButtonNomComer)
                            .addComponent(jRadioButtonCiudad)
                            .addComponent(jRadioButtonNinguno))
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addComponent(jButtonBuscarZonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonNinguno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCiudad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNomComer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarZonas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCiudadActionPerformed
        jComboBoxFiltro.removeAllItems();
        for (int i = 0; i < ciudades.size(); i++) {
            jComboBoxFiltro.addItem(ciudades.get(i).getNombreCiudad());
        }
    }//GEN-LAST:event_jRadioButtonCiudadActionPerformed

    private void jButtonBuscarZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarZonasActionPerformed
        try {
            String empresa = jComboBoxEmpresas.getSelectedItem().toString();
            String dataf = jComboBoxFiltro.getSelectedItem().toString();
            if (jRadioButtonNinguno.isSelected()) {
                
            } else if (jRadioButtonCiudad.isSelected()) {
                allZonas = handler.showRepZonasFiltroCiudad(empresa,dataf);
                updateTable();
            } else if (jRadioButtonEstado.isSelected()) {
                allZonas = handler.showRepZonasFiltroEstado(empresa,dataf);
                updateTable();
            } else if (jRadioButtonNomComer.isSelected()) {
                allZonas = handler.showRepZonasFiltroNomComer(empresa,dataf);
                updateTable();
            }
        } catch (Exception e) {
                allZonas = handler.showRepAllZonas();
                updateTable();
        }
    }//GEN-LAST:event_jButtonBuscarZonasActionPerformed

    private void jRadioButtonEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEstadoActionPerformed
        jComboBoxFiltro.removeAllItems();
        for (int i = 0; i < estados.size(); i++) {
            jComboBoxFiltro.addItem(estados.get(i).getNombre());
        }
    }//GEN-LAST:event_jRadioButtonEstadoActionPerformed

    private void jRadioButtonNomComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNomComerActionPerformed
        jComboBoxFiltro.removeAllItems();
        for (int i = 0; i < comercios.size(); i++) {
            jComboBoxFiltro.addItem(comercios.get(i).getNombreComercial());
        }
    }//GEN-LAST:event_jRadioButtonNomComerActionPerformed

    private void jRadioButtonNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNingunoActionPerformed
        jComboBoxFiltro.removeAllItems();
    }//GEN-LAST:event_jRadioButtonNingunoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new Principal(tipo).setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBuscarZonas;
    private javax.swing.JComboBox<String> jComboBoxEmpresas;
    private javax.swing.JComboBox jComboBoxFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButtonCiudad;
    private javax.swing.JRadioButton jRadioButtonEstado;
    private javax.swing.JRadioButton jRadioButtonNinguno;
    private javax.swing.JRadioButton jRadioButtonNomComer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
